version: '3.8'
services:
  app:
    image: manage-users-and-subscriptions
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ManageUsersAndSubscriptionsDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ManageUsersAndSubscriptionsDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"